Repository selsa-inube/inubekit-tag, pull requests merged in 2024-04, with the labels that each got.

#2 Refactor component to use new token structure
  package-lock.json
  package.json
  src/Tag/Tag.stories.tsx
  src/Tag/index.tsx
  src/Tag/props.ts
  src/Tag/styles.js
  src/index.ts
  vite.config.ts
Labels: major

#4 Publish new version 2.0.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: documentation

#5 Add auto publish
  .autorc.json
  .github/workflows/auto-release.yml
  .gitignore
  package-lock.json
  package.json
Labels: enhancement

#6 Refactor component so it uses theme from ThemeContext
  src/Tag/index.tsx
Labels: major

#7 fix(tag): refactor component so it uses theme from ThemeContext
  src/Tag/index.tsx
Labels: minor

#8 Extend component to include "removable" boolean prop
  package-lock.json
  package.json
  src/Tag/Tag.stories.tsx
  src/Tag/index.tsx
  src/Tag/styles.js
  vite.config.ts
Labels: enhancement

#9 Update workflow in order to avoid merges with failed builds
  .github/workflows/auto-release.yml
Labels: minor
